services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    container_name: filebeat-test-es-node
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
      - secondary_net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.3
    container_name: filebeat-test-kibana-node
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false
    ports:
      - 5601:5601
    networks:
      - elastic
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.15.3
    container_name: filebeat-node1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./logs:/tmp/filebeat_logs  # Mount directory for log files to monitor
    networks:
      - elastic
      - secondary_net
    depends_on:
      - elasticsearch
      - kibana
    command: filebeat -e  # Start filebeat with console output

volumes:
  esdata:
    driver: local

networks:
  elastic:
    driver: bridge
  secondary_net:
    driver: bridge
