filebeat.inputs:
  - type: filestream
    enabled: true
    paths:
      - /tmp/filebeat_logs/*.log  # Path to JSON log files
    parsers:
      - ndjson:
          target: ""  # Extract fields at the root level
    prospector:
      scanner:
        fingerprint:
          enabled: false  # Keep fingerprint disabled

processors:
  - dissect:
      tokenizer: "%{timestamp} %{milliseconds} %{loglevel} [%{component}:%{line}][%{filename}] %{log_message}"
      field: "message"
      target_prefix: "dissect"

  - script:
      lang: javascript
      source: >
        function process(event) {
          var timestamp = event.Get("dissect.timestamp");
          var milliseconds = event.Get("dissect.milliseconds");
          if (timestamp && milliseconds) {
            var customTimestamp = timestamp + "T" + milliseconds + "Z";
            event.Put("custom_timestamp", customTimestamp);
          }
        }

  - timestamp:
      field: "custom_timestamp"
      layouts:
        - "2006-01-02T15:04:05,000Z"
      timezone: "UTC"
      ignore_missing: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]  # Link to Elasticsearch container

# Enable debug logging
logging.level: debug
logging.selectors: ["*"]
