services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1
    container_name: es-node1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
      - secondary_net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.1
    container_name: kibana-node1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false
    ports:
      - 5601:5601
    networks:
      - elastic
    depends_on:
      - elasticsearch

  packetbeat:
    image: docker.elastic.co/beats/packetbeat:8.15.1
    build: ./packetbeat
    container_name: packetbeat1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    volumes:
      - ./packetbeat.yml:/usr/share/packetbeat/packetbeat.yml
      - ./logs:/tmp/packetbeat_logs
      - /proc:/hostfs/proc:ro  # Mount host /proc
      - /sys:/hostfs/sys:ro    # Mount host /sys
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      - elastic
      - secondary_net
    depends_on:
      - elasticsearch
      - kibana
    command: packetbeat -E system.hostfs=/hostfs  # Corrected flag format

volumes:
  esdata:
    driver: local

networks:
  elastic:
    driver: bridge
  secondary_net:
    driver: bridge
