# packetbeat.interfaces.device: any
packetbeat:
  interfaces:
    - device: eth1
    - device: eth0


packetbeat.protocols:
  - type: http
    ports: [80, 9200, 5601]

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

logging.level: debug
logging.to_files: true
logging.files:
  path: /tmp/packetbeat_logs
  name: packetbeat.log