version: "3.8"

services:
  es-business:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.1
    container_name: es-business
    environment:
      - node.name=es-business
      - cluster.name=business-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.monitoring.collection.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9201:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata-business:/usr/share/elasticsearch/data
    networks:
      - elastic

  kibana-business:
    image: docker.elastic.co/kibana/kibana:8.18.1
    container_name: kibana-business
    environment:
      - ELASTICSEARCH_HOSTS=http://es-business:9200
      - xpack.security.enabled=false
    ports:
      - "5602:5601"
    depends_on:
      - es-business
    networks:
      - elastic

  es-monitor:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.1
    container_name: es-monitor
    environment:
      - node.name=es-monitor
      - cluster.name=monitoring-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.monitoring.collection.enabled=false

      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata-monitor:/usr/share/elasticsearch/data
    networks:
      - elastic

  kibana-monitor:
    image: docker.elastic.co/kibana/kibana:8.18.1
    container_name: kibana-monitor
    environment:
      - ELASTICSEARCH_HOSTS=http://es-monitor:9200
      - xpack.security.enabled=false
      - SERVER_HOST=0.0.0.0

    ports:
      - "5601:5601"
    depends_on:
      - es-monitor
    networks:
      - elastic
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:8.18.1
    container_name: metricbeat
    user: root
    volumes:
      - ./metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
    depends_on:
      - es-business
      - es-monitor
    networks:
      - elastic

volumes:
  esdata-business:
    driver: local
  esdata-monitor:
    driver: local

networks:
  elastic:
    driver: bridge
