metricbeat.modules:
  - module: elasticsearch
    metricsets: ["node", "node_stats", "cluster_stats"]
    period: 10s
    hosts: ["http://es-business:9200"]
    xpack.enabled: true

  - module: elasticsearch
    metricsets: ["node", "node_stats", "cluster_stats"]
    period: 10s
    hosts: ["http://es-business-2:9999"] # Intentionally broken for reproduction
    xpack.enabled: true

  - module: elasticsearch
    metricsets: ["node", "node_stats", "cluster_stats"]
    period: 10s
    hosts: ["http://es-monitor:9200"]
    xpack.enabled: true

  - module: kibana
    metricsets: ["stats"]
    period: 10s
    hosts: ["http://kibana-business:5601"]
    xpack.enabled: true

  - module: kibana
    metricsets: ["stats"]
    period: 10s
    hosts: ["http://kibana-monitor:5601"]
    xpack.enabled: true

output.elasticsearch:
  hosts: ["http://es-monitor:9200"] ## Monitoring cluster
  # Optional protocol and basic auth credentials.
  #protocol: "https"
  #username: "elastic"
  #password: "changeme"

# Reproduction Note:
# Intentionally set es-business-2 port to 9999 to simulate Metricbeat failure.
# Result: Kibana Stack Monitoring UI still shows the cluster, but only with the healthy node(s).
# The entire cluster does NOT disappear from the UI due to this error.